### ISSUE TITLE
The latest version, sleep error

### ISSUE THREAD

**Issue by junguoguo2017** [Juan-VC/Hackintosh-macOS-Catalina-on-Dell-G7-7588#26]
panic(cpu 0 caller 0xffffff800b891b2c): Sleep transition timed out after 180 seconds while entering darkwake on way to sleep. Suspected bundle: com.apple.driver.usb.AppleUSBXHCI. Thread 0x5037f.
Failure code:: 0x076f4382 00000031

Backtracing panicked thread because kernel_stack is NULL for specified thread
Backtrace (CPU 0), Frame : Return Address
0xffffff8208463930 : 0xffffff800b1215cd 
0xffffff8208463980 : 0xffffff800b25a3c5 
0xffffff82084639c0 : 0xffffff800b24bf7e 
0xffffff8208463a10 : 0xffffff800b0c7a40 
0xffffff8208463a30 : 0xffffff800b120c97 
0xffffff8208463b30 : 0xffffff800b121087 
0xffffff8208463b80 : 0xffffff800b8c2d7c 
0xffffff8208463bf0 : 0xffffff800b891b2c 
0xffffff8208463ea0 : 0xffffff800b814aaa 
0xffffff8208463ec0 : 0xffffff800b163545 
0xffffff8208463f40 : 0xffffff800b163071 
0xffffff8208463fa0 : 0xffffff800b0c713e 

BSD process name corresponding to current thread: kernel_task

Mac OS version:
19E266

Kernel version:
Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Kernel UUID: AB0AA7EE-3D03-3C21-91AD-5719D79D7AF6
Kernel slide:     0x000000000ae00000
Kernel text base: 0xffffff800b000000
__HIB  text base: 0xffffff800af00000
System model name: MacBookPro15,2 (Mac-827FB448E656EC26)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 30033540851034

**Comment by Juan-VC** [comment]
Did you update every kext + opencore? Also, remember to disable hibernate (sudo pmset -a hibernatemode 0) and cfg-lock. CFG-Lock could be the cause of the panic.

**Comment by Juan-VC** [comment]
Your uptime is inconsistent with the latest version available, prefferaly update with yerterday's release 0.0.4.

**Comment by junguoguo2017** [comment]
Yes, it is the latest version. There is no problem with the last version. An abnormal shutdown occurred after the update yesterday

**Comment by Juan-VC** [comment]
I am currently with the latest files for more than 10hrs and haven't faced any problem. I will try to see if I get any issues when sleeping as I would require more info to find the cause. If you keep facing the problem, delete SSDT-USBX.aml found in OC/ACPI to see if it helps, it has been the only USB related modification since 0.0.2 and the issues point to either be USB and/or power related.

**Comment by junguoguo2017** [comment]
There was another abnormal shutdown last night. I left it on and waited for it to go to sleep, only to find the next morning that it was switched off. Last abnormal shutdown

**Comment by Juan-VC** [comment]
Backup and reinstall something is messed up for you I guess, I have had no panics nor any other users. Replace once again every OC file.

**Comment by junguoguo2017** [comment]
panic(cpu 2 caller 0xffffff8001691b2c): Sleep transition timed out after 180 seconds while entering darkwake on way to sleep. Suspected bundle: com.apple.iokit.IOUSBHostFamily. Thread 0x30dd1.
Failure code:: 0x076f4382 00000031

Backtracing panicked thread because kernel_stack is NULL for specified thread
Backtrace (CPU 2), Frame : Return Address
0xffffff81fe4ab930 : 0xffffff8000f215cd 
0xffffff81fe4ab980 : 0xffffff800105a3c5 
0xffffff81fe4ab9c0 : 0xffffff800104bf7e 
0xffffff81fe4aba10 : 0xffffff8000ec7a40 
0xffffff81fe4aba30 : 0xffffff8000f20c97 
0xffffff81fe4abb30 : 0xffffff8000f21087 
0xffffff81fe4abb80 : 0xffffff80016c2d7c 
0xffffff81fe4abbf0 : 0xffffff8001691b2c 
0xffffff81fe4abea0 : 0xffffff8001614aaa 
0xffffff81fe4abec0 : 0xffffff8000f63545 
0xffffff81fe4abf40 : 0xffffff8000f63071 
0xffffff81fe4abfa0 : 0xffffff8000ec713e 

BSD process name corresponding to current thread: kernel_task

Mac OS version:
19E266

Kernel version:
Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Kernel UUID: AB0AA7EE-3D03-3C21-91AD-5719D79D7AF6
Kernel slide:     0x0000000000c00000
Kernel text base: 0xffffff8000e00000
__HIB  text base: 0xffffff8000d00000
System model name: MacBookPro15,2 (Mac-827FB448E656EC26)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 15078262992666

**Comment by junguoguo2017** [comment]
Abnormal shutdowns occurred several times

**Comment by Juan-VC** [comment]
Reinstall if you haven´t if you have you either have faulty storage or wrong settings.
