### ISSUE TITLE
Occasionally abnormal shutdown

### ISSUE THREAD

**Issue by junguoguo2017** [Juan-VC/Hackintosh-macOS-Catalina-on-Dell-G7-7588#6]
When working, abnormal shutdown

**Comment by Juan-VC** [comment]
Can you provide kernel logs? I have never face an abnormal shutdown nor anyone who uses the configuration files. Was it properly configured?

**Comment by junguoguo2017** [comment]
I forgot to save it. Next time I save a copy, the probability of occurrence is quite large. I'm a 14.6 system and I show up every few days.

**Comment by junguoguo2017** [comment]
> 您可以提供内核日志吗？我从未遇到过异常关机，也从未使用过配置文件的任何人。是否配置正确？

My network card is 1820A. Bluetooth wifi is working fine, I wonder if it's the problem

**Comment by Juan-VC** [comment]
That may be the problem you know, I stopped supporting Mojave long ago, maybe try switching to Catalina? Curious about why you have not updated yet. DW1820A could also be the problem, it needs some special treatment to configure it.

**Comment by Juan-VC** [comment]
ASPM enabled causes issues with DW1820 and macOS, so it must be disabled

**Comment by junguoguo2017** [comment]
Direct upgrade should not succeed, I am not sure, did not try. And my computer is equipped with a lot of working software and environment. I wonder if it will work properly after the update. Or, reinstall the system and restore it with a time machine?

**Comment by junguoguo2017** [comment]
> ASPM
Is it disabled in the BIOS?

**Comment by Juan-VC** [comment]
> Direct upgrade should not succeed, I am not sure, did not try. And my computer is equipped with a lot of working software and environment. I wonder if it will work properly after the update. Or, reinstall the system and restore it with a time machine?

Keep your current working boot folder and create a dummy USB and try copying to it the newest  Clover folder, so Clover gets updated and the newest config files get pulled. ASPM is disabled via config.plist, when you get the USB with the newest files email me and I will send you a file with aspm disabled

**Comment by junguoguo2017** [comment]
> > Direct upgrade should not succeed, I am not sure, did not try. And my computer is equipped with a lot of working software and environment. I wonder if it will work properly after the update. Or, reinstall the system and restore it with a time machine?
> 
> Keep your current working boot folder and create a dummy USB and try copying to it the newest Clover folder, so Clover gets updated and the newest config files get pulled. ASPM is disabled via config.plist, when you get the USB with the newest files email me and I will send you a file with aspm disabled

Did you say usb installation image file? I have to say 10.15, right. I'll do as you say.

**Comment by Juan-VC** [comment]
I meant to create a USB to test upgrading to Catalina using my latest files, you might have outdated ones.

**Comment by junguoguo2017** [comment]
> meant

I may not know how to upgrade with usb; I used usb to install the system. My English is not very good, I use the translation software

**Comment by Juan-VC** [comment]
Set up this repo Clover files to a new USB, try upgrading to Catalina by booting macOS then going to software update and just update like a real mac. It should work so you can with the peace of mind replace your actual Clover folder with the new one used on the USB knowing it works correctly.

**Comment by junguoguo2017** [comment]
> 将此仓库的Clover文件设置为新的USB，尝试通过启动macOS升级到Catalina，然后进行软件更新，就像真实的mac一样进行更新。它应该可以正常工作，因此您可以放心使用USB上的新文件夹替换实际的Clover文件夹，因为它知道它可以正常工作。

Ok, I'll give it a try. Things may not go well and we may need your help

**Comment by junguoguo2017** [comment]
> > 内置仓库的Clover文件设置为新的USB，尝试通过启动macOS升级到Catalina，然后进行软件更新，就像真实的mac一样进行更新。它应该可以正常工作，因此您可以放心使用USB上的新文件夹替换实际的Clover文件夹，因为它知道它可以正常工作。
> 
> 好的，我会尝试的。事情可能不会顺利进行，我们可能需要您的帮助
I forgot to tell you that the clover of my current system 14.6 is the clover of your project.

**Comment by Juan-VC** [comment]
> > 内置仓库的Clover文件设置为新的USB，尝试通过启动macOS升级到Catalina，然后进行软件更新，就像真实的mac一样进行更新。它应该可以正常工作，因此您可以放心使用USB上的新文件夹替换实际的Clover文件夹，因为它知道它可以正常工作。
> 
> 好的，我会尝试的。事情可能不会顺利进行，我们可能需要您的帮助
> I forgot to tell you that the clover of my current system 14.6 is the clover of your project.

Good is the latest yet still DW1820A requires a special property injection, you could also try the new OpenCore bootloader guide I just pushed today. Because of you and other people who may want to use that card, there is a config file for OpenCore that injects the appropriate data.

**Comment by junguoguo2017** [comment]
I have not used opencore. Is it better to divide your project into two parts: opencore and clover, so that we can choose which one to use? I wonder if it will be effective to directly replace clover to efi file.

**Comment by Juan-VC** [comment]
You can still use clover, I created a separate branch for it, but it may not be updated anymore.

**Comment by junguoguo2017** [comment]
> 您仍然可以使用三叶草，我为此创建了一个单独的分支，但是可能不再更新了。

Ok, I will study opencore when I have time later. I wonder whether opencore is more stable than clover at present. Thank you

**Comment by Juan-VC** [comment]
As per the OpenCore guide states, it is. The future of Hackintosh is OpenCore so switching will be necessary sometime.

**Comment by junguoguo2017** [comment]
> As per the OpenCore guide states, it is. The future of Hackintosh is OpenCore so switching will be necessary sometime.
I replaced the latest clover and found that the bluetooth could not be recognized

**Comment by Juan-VC** [comment]
I placed my opencore usbmap to clover but it then seems to break Bluetooth, I placed USBPorts.kext back, try it again

**Comment by Juan-VC** [comment]
I am closing the issue because it is no longer related to random kernel panics causing to reboot.

**Comment by junguoguo2017** [comment]
> 我正在解决此问题，因为它不再与导致重启的随机内核崩溃有关。

Ok, I'll try again
